### ISSUE TITLE
ERROR: Command errored out with exit status 1:

### ISSUE THREAD

**Issue by erickyun** [Neo-Oli/Termux-Mpv#13]
```
$ pip install git+https://github.com/Neo-Oli/Termux-Mpv
Collecting git+https://github.com/Neo-Oli/Termux-Mpv
  Cloning https://github.com/Neo-Oli/Termux-Mpv to /data/data/com.termux/files/usr/tmp/pip-req-build-gufzp_74
  Running command git clone -q https://github.com/Neo-Oli/Termux-Mpv /data/data/com.termux/files/usr/tmp/pip-req-build-gufzp_74
  Resolved https://github.com/Neo-Oli/Termux-Mpv to commit a6ec1a865ccd342b2281761835ab33c11fb0638e
    ERROR: Command errored out with exit status 1:
     command: /data/data/com.termux/files/usr/bin/python3 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/data/data/com.termux/files/usr/tmp/pip-req-build-gufzp_74/setup.py'"'"'; __file__='"'"'/data/data/com.termux/files/usr/tmp/pip-req-build-gufzp_74/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /data/data/com.termux/files/usr/tmp/pip-pip-egg-info-fxi78wn5
         cwd: /data/data/com.termux/files/usr/tmp/pip-req-build-gufzp_74/
    Complete output (11 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/setuptools/__init__.py", line 18, in <module>
        from setuptools.dist import Distribution
      File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/setuptools/dist.py", line 38, in <module>
        from setuptools import windows_support
      File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/setuptools/windows_support.py", line 2, in <module>
        import ctypes
      File "/data/data/com.termux/files/usr/lib/python3.10/ctypes/__init__.py", line 8, in <module>
        from _ctypes import Union, Structure, Array
    ImportError: dlopen failed: cannot locate symbol "ffi_closure_free" referenced by "/data/data/com.termux/files/usr/lib/python3.10/lib-dynload/_ctypes.cpython-310.so"...
    ----------------------------------------
WARNING: Discarding git+https://github.com/Neo-Oli/Termux-Mpv. Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
WARNING: You are using pip version 21.2.3; however, version 21.2.4 is available.
You should consider upgrading via the '/data/data/com.termux/files/usr/bin/python3 -m pip install --upgrade pip' command.
$
```

**Comment by Neo-Oli** [comment]
Works for me.
What is your output of `termux-info`? Any updatable packages?

**Comment by Neo-Oli** [comment]
Refer to this: https://github.com/termux/termux-packages/issues/6726
